!obj:pylearn2.train.Train {
    dataset: &train !obj:contest_dataset.ContestDataset {
        which_set: 'train',
        start: 1,
        stop: 4010,
        preprocessor: !obj:pylearn2.datasets.preprocessing.GlobalContrastNormalization {}
    },
    model: !obj:pylearn2.models.mlp.MLP {
        batch_size: 50,
        layers: [
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h0',
                     dim: 4096,
                     max_col_norm: 1.9365,
                     sparse_init: 22,
                     sparse_stdev: .005
                 },
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h1',
                     dim: 4096,
                     max_col_norm: 1.9365,
                     sparse_init: 22,
                     sparse_stdev: .005
                 },
                 !obj:pylearn2.models.mlp.RectifiedLinear {
                     layer_name: 'h2',
                     dim: 4096,
                     max_col_norm: 1.9365,
                     sparse_init: 22,
                     sparse_stdev: .005
                 },
                 !obj:pylearn2.models.mlp.Softmax {
                     layer_name: 'y',
                     max_col_norm: 1.9365,
                     n_classes: 7,
                     irange: .005
                 }
            ],
        nvis: 2304,
        dropout_include_probs: [ .5, .5, .5, 1 ],
        dropout_input_include_prob: .5,
        dropout_input_scale: 1.,
    },
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: .08,
        init_momentum: .8,
        monitoring_dataset:
        {
            'train' : *train,
            'valid' : !obj:contest_dataset.ContestDataset {
                        which_set: 'train',
                        start: 4010,
                        stop: 4178,
                        preprocessor: !obj:pylearn2.datasets.preprocessing.GlobalContrastNormalization {}
                      },
        },
        cost: !obj:pylearn2.costs.cost.MethodCost {
                method: 'cost_from_X',
                supervised: 1
        },
        termination_criterion: !obj:pylearn2.termination_criteria.MonitorBased {
            channel_name: "valid_y_misclass",
            prop_decrease: 0.,
            N: 100
        },
        update_callbacks: !obj:pylearn2.training_algorithms.sgd.ExponentialDecay {
            decay_factor: 1.00004,
            min_lr: .000001
        }
    },
    extensions: [
        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
             channel_name: 'valid_y_misclass',
             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
        },
        !obj:pylearn2.training_algorithms.sgd.MomentumAdjustor {
            start: 1,
            saturate: 250,
            final_momentum: .99
        }
    ],
    save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}.pkl",
    save_freq: 1
}
